### ISSUE TITLE
Uncaught, unspecified "error" event

### ISSUE THREAD

**Issue by jeffzimmerlin** [iriscouch/dnsd#18]
Hello,
When running dnsd in production, we occasionally get this error:

```
events.js:165
throw err;
^

Error: Uncaught, unspecified "error" event. (Error processing request)
at Server.emit (events.js:163:17)
at Server.on_udp (/usr/local/lib/node_modules/dnsd/server.js:177:10)
at Socket.<anonymous> (/usr/local/lib/node_modules/dnsd/server.js:45:54)
at emitTwo (events.js:106:13)
at Socket.emit (events.js:191:7)
at UDP.onMessage (dgram.js:540:8)
```

It happens about once a day, sometimes more.

Here's a simplified version of our app:

```js
var dnsd = tk.require('dnsd');

var dns_server = dnsd.createServer(
	function(req, res){
		try{
			//var hostname = <insert random app logic>;

			if(question.type=='A'){
				res.answer.push({
					name: hostname,
					type: 'A',
					data: ip,
					ttl: 604800
				});
			}
			res.end();
		}
		catch(e){
			res.end();
		}
	}
)
.zone(
	'ourdomain.com',
	'ns1.ourdomain.com',
	'support@ourdomain.com',
	'now',
	'2h',
	'30m',
	'2w',
	'52w'
)
.listen(53);
```

Is this an issue with dnsd?  Or is there something we should be doing differently in our app code?

Thanks so much!

**Comment by EmRa228** [comment]
This is my issue too!
